### ISSUE TITLE
Items with a destock quantity ignored on import

### ISSUE THREAD

**Issue by Cygnus-Altair** [xscr33m/TraderPlusEditor#3]
**Describe the bug**

Items with a destock quantity ignored on import.
For example:
"BookThreeMenInABoat,0.996,100,1,800,200"
will be imported while:
"BrassKnuckles_Shiny,0.996,100,1,150,50,0.75",

Will not be imported

**To Reproduce**
Import a json which has items with a destock quantity after the sell price.

**Expected behavior**
All products imported, instead of just ones without the destock ratio.

**Comment by xscr33m** [comment]
**confirmed!**
Reason: this variable is not being recognised during import because I simple overseen it in the documentary. I'll add it as soon as possible. For now, only items with no destock-qty will show up in editor.

Thank you so much for this detailed report!

**Comment by xscr33m** [comment]
New version 1.0.0.2 is out now! 

[Get it here](https://github.com/xscr33m/TraderPlusEditor/releases/tag/v1.0.0.2)

Now destock coeff added as optional value with alle the features from the other values!
