### ISSUE TITLE
I can't export files?

### ISSUE THREAD

**Issue by thorgorn** [xscr33m/TraderPlusEditor#4]
I can't export a .json after editing the file, I am editing my price config all seems okay but the export file option stays greyed out? I have tried running as administrator etc makes no difference it will not let me export my changes?

**Comment by xscr33m** [comment]
Hi there, thank you for reporting! 

Please be sure to save the changes with the "Save and Next"-Button. 
After that the Button "Export File" will be enabled. If the File was already exported, the button then will disables and waits for new changes. 

You'll need to make actual value changes for the export button to become enabled. Only clicking the Save-Button does not changes the values. No changed values = no export needed
![2023-05-26 12_07_03-xscr33m's TraderPlusEditor](https://github.com/xscr33m/TraderPlusEditor/assets/106840889/523e762d-6391-496d-910f-30be9cadaa66)

**Comment by thorgorn** [comment]
It was because I was selecting "Set all" and this for some reason doesn't enable the Save and next option but after manually changing one field this now works. Thanks :)

**Comment by xscr33m** [comment]
Alright, thank you for the explanation! 
Then the following is the true issue: _SetAll buttons do not enable exportButton._
 
I'll fix this as soon as possible.

**Comment by xscr33m** [comment]
Fixed this issue in Version 1.0.0.3 ✔

[Get it here](https://github.com/xscr33m/TraderPlusEditor/releases/download/v1.0.0.3/xscr33m.s.TraderPlusEditor.zip)

Also including automated check  for updates and some performance/stability optimizations. Let me know your feedback! 

[![Logo](https://cdn.discordapp.com/attachments/1103457256164569120/1109278528354127982/Join_Discord-logo.png)](https://discord.com/invite/K9mkHyuGG8)
